services:
  fastapi:
    build: .
    container_name: fastapi_app
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - db_data:/app/db
    environment:
      - DATABASE_URL=sqlite:///./db/database.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:
