services:
  fastapi:
    build: .
    container_name: fastapi_app
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - db_data:/app/db
    environment:
      - DATABASE_URL=sqlite:///./db/database.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
