name: CI - FastAPI Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest httpx coverage

      - name: Build Docker image
        run: docker-compose build

      - name: Run Docker container
        run: docker-compose up -d

      - name: Wait for FastAPI container to be healthy
        run: |
          for i in {1..30}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' fastapi_app)
            echo "Current container health: $STATUS"
            if [ "$STATUS" == "healthy" ]; then
              echo "FastAPI container is healthy."
              break
            fi
            sleep 2
          done

      - name: Run tests with coverage
        run: |
          docker exec fastapi_app coverage run -m pytest app/test_main.py
          docker exec fastapi_app coverage report
          docker exec fastapi_app coverage xml

      - name: Cleanup
        run: docker-compose down
