name: CI - FastAPI Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest httpx

      - name: Build Docker image
        run: docker-compose build

      - name: Run Docker container
        run: docker-compose up -d

      - name: Wait for FastAPI to be ready
        run: |
          for i in {1..60}; do
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/docs) || echo "curl failed"
              if [ "$STATUS" = "200" ]; then
                  echo "✅ FastAPI is ready"
                  break
              else
                  echo "🔁 Waiting for FastAPI... ($i/60) — Status: $STATUS"
                  sleep 2
              fi
          done

      - name: Run tests
        run: pytest

      - name: Cleanup
        run: docker-compose down
