name: CI - FastAPI Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov httpx

      - name: Build and start containers
        run: docker-compose up --build -d

      - name: Wait for FastAPI to be ready
        run: |
          for i in {1..30}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/docs)
            if [ "$STATUS" = "200" ]; then
              echo "✅ FastAPI is ready"
              break
            else
              echo "🔁 Waiting for FastAPI... ($i/30) — Status: $STATUS"
              sleep 2
            fi
          done

      - name: Run tests with coverage
        run: |
          pytest --cov=app app/test_main.py

      - name: Upload coverage report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: coverage-report
          path: htmlcov/  # generated if you run pytest with --cov-report=html

      - name: Cleanup containers
        run: docker-compose down
