name: CI - FastAPI Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest httpx

      - name: Build and start Docker containers
        run: docker compose up --build -d

      - name: Wait for FastAPI to be ready
        run: |
          for i in {1..60}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/docs) || echo "curl failed"
            if [ "$STATUS" = "200" ]; then
              echo "✅ FastAPI is ready"
              break
            else
              echo "🔁 Waiting for FastAPI... ($i/60) — Status: $STATUS"
              sleep 2
            fi
          done
          if [ "$STATUS" != "200" ]; then
            echo "❌ FastAPI did not start in time"
            docker compose logs fastapi_app
            exit 1
          fi

      - name: Run tests
        run: pytest app/test_main.py

      - name: Cleanup
        run: docker compose down
